#!/bin/bash
PATH="$PWD/node_modules/.bin":$PATH
set -e

build() {
  set -x
  prisma generate
  rm -rfv dist
  microbundle -i src/main.ts --tsconfig tsconfig.build.json --no-generateTypes --no-sourcemap --no-compress --no-pkg-main --target node -f cjs -o dist
  set +x
}

"$@"
